from django.db import models


class Transaction(models.Model):

    amount        = models.FloatField()
    status        = models.CharField(max_length=30)
    anomaly_score = models.FloatField(default=0)
    timestamp     = models.DateTimeField(auto_now_add=True)

    V1 = models.FloatField(default=0)
    V2 = models.FloatField(default=0)
    V3 = models.FloatField(default=0)
    V4 = models.FloatField(default=0)
    V5 = models.FloatField(default=0)
    V6 = models.FloatField(default=0)
    V7 = models.FloatField(default=0)
    V8 = models.FloatField(default=0)
    V9 = models.FloatField(default=0)
    V10 = models.FloatField(default=0)
    V11 = models.FloatField(default=0)
    V12 = models.FloatField(default=0)
    V13 = models.FloatField(default=0)
    V14 = models.FloatField(default=0)
    V15 = models.FloatField(default=0)
    V16 = models.FloatField(default=0)
    V17 = models.FloatField(default=0)
    V18 = models.FloatField(default=0)
    V19 = models.FloatField(default=0)
    V20 = models.FloatField(default=0)
    V21 = models.FloatField(default=0)
    V22 = models.FloatField(default=0)
    V23 = models.FloatField(default=0)
    V24 = models.FloatField(default=0)
    V25 = models.FloatField(default=0)
    V26 = models.FloatField(default=0)
    V27 = models.FloatField(default=0)
    V28 = models.FloatField(default=0)


# In models.py, add this field to SecurityAuditLog:
class SecurityAuditLog(models.Model):

    amount            = models.FloatField()
    anomaly_score     = models.FloatField(default=0)
    timestamp         = models.DateTimeField(auto_now_add=True)
    reason            = models.CharField(max_length=100, null=True, blank=True)
    shap_values       = models.JSONField(null=True, blank=True)
    is_false_positive = models.BooleanField(default=False)

    # Behavioural flag breakdown (for pie chart)
    is_vpn            = models.BooleanField(default=False)
    is_international  = models.BooleanField(default=False)
    is_new_device     = models.BooleanField(default=False)
    is_highrisk       = models.BooleanField(default=False)
    is_high_amount    = models.BooleanField(default=False)

    V1 = models.FloatField(default=0)
    V2 = models.FloatField(default=0)
    V3 = models.FloatField(default=0)
    V4 = models.FloatField(default=0)
    V5 = models.FloatField(default=0)
    V6 = models.FloatField(default=0)
    V7 = models.FloatField(default=0)
    V8 = models.FloatField(default=0)
    V9 = models.FloatField(default=0)
    V10 = models.FloatField(default=0)
    V11 = models.FloatField(default=0)
    V12 = models.FloatField(default=0)
    V13 = models.FloatField(default=0)
    V14 = models.FloatField(default=0)
    V15 = models.FloatField(default=0)
    V16 = models.FloatField(default=0)
    V17 = models.FloatField(default=0)
    V18 = models.FloatField(default=0)
    V19 = models.FloatField(default=0)
    V20 = models.FloatField(default=0)
    V21 = models.FloatField(default=0)
    V22 = models.FloatField(default=0)
    V23 = models.FloatField(default=0)
    V24 = models.FloatField(default=0)
    V25 = models.FloatField(default=0)
    V26 = models.FloatField(default=0)
    V27 = models.FloatField(default=0)
    V28 = models.FloatField(default=0)