# Generated by Django 6.0.3 on 2026-05-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("anomaly_score", models.FloatField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(blank=True, max_length=100, null=True)),
                ("shap_values", models.JSONField(blank=True, null=True)),
                ("is_false_positive", models.BooleanField(default=False)),
                ("V1", models.FloatField(default=0)),
                ("V2", models.FloatField(default=0)),
                ("V3", models.FloatField(default=0)),
                ("V4", models.FloatField(default=0)),
                ("V5", models.FloatField(default=0)),
                ("V6", models.FloatField(default=0)),
                ("V7", models.FloatField(default=0)),
                ("V8", models.FloatField(default=0)),
                ("V9", models.FloatField(default=0)),
                ("V10", models.FloatField(default=0)),
                ("V11", models.FloatField(default=0)),
                ("V12", models.FloatField(default=0)),
                ("V13", models.FloatField(default=0)),
                ("V14", models.FloatField(default=0)),
                ("V15", models.FloatField(default=0)),
                ("V16", models.FloatField(default=0)),
                ("V17", models.FloatField(default=0)),
                ("V18", models.FloatField(default=0)),
                ("V19", models.FloatField(default=0)),
                ("V20", models.FloatField(default=0)),
                ("V21", models.FloatField(default=0)),
                ("V22", models.FloatField(default=0)),
                ("V23", models.FloatField(default=0)),
                ("V24", models.FloatField(default=0)),
                ("V25", models.FloatField(default=0)),
                ("V26", models.FloatField(default=0)),
                ("V27", models.FloatField(default=0)),
                ("V28", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("status", models.CharField(max_length=30)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("V1", models.FloatField(default=0)),
                ("V2", models.FloatField(default=0)),
                ("V3", models.FloatField(default=0)),
                ("V4", models.FloatField(default=0)),
                ("V5", models.FloatField(default=0)),
                ("V6", models.FloatField(default=0)),
                ("V7", models.FloatField(default=0)),
                ("V8", models.FloatField(default=0)),
                ("V9", models.FloatField(default=0)),
                ("V10", models.FloatField(default=0)),
                ("V11", models.FloatField(default=0)),
                ("V12", models.FloatField(default=0)),
                ("V13", models.FloatField(default=0)),
                ("V14", models.FloatField(default=0)),
                ("V15", models.FloatField(default=0)),
                ("V16", models.FloatField(default=0)),
                ("V17", models.FloatField(default=0)),
                ("V18", models.FloatField(default=0)),
                ("V19", models.FloatField(default=0)),
                ("V20", models.FloatField(default=0)),
                ("V21", models.FloatField(default=0)),
                ("V22", models.FloatField(default=0)),
                ("V23", models.FloatField(default=0)),
                ("V24", models.FloatField(default=0)),
                ("V25", models.FloatField(default=0)),
                ("V26", models.FloatField(default=0)),
                ("V27", models.FloatField(default=0)),
                ("V28", models.FloatField(default=0)),
            ],
        ),
    ]
