# Generated by Django 6.0.3 on 2026-05-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fraud_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="anomaly_score",
            field=models.FloatField(default=0),
        ),
    ]
