# Generated by Django 6.0.3 on 2026-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fraud_app", "0002_transaction_anomaly_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityauditlog",
            name="is_high_amount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="securityauditlog",
            name="is_highrisk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="securityauditlog",
            name="is_international",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="securityauditlog",
            name="is_new_device",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="securityauditlog",
            name="is_vpn",
            field=models.BooleanField(default=False),
        ),
    ]
